name: backend build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Set the value
          id: step_one
          run: |
            cat ./backend/lorect_ssh
#       - name: multiple command
#         uses: appleboy/ssh-action@master
#         with:
#           host: 46.31.79.30
# #           username: root
# #           key: ./lorect_ssh
#           passphrase: lorect_ssh
#           password: .Sh0p2@nk@.
# #           port: 22
#           script: |
#             cd ~/bilal
#             bash deploy.sh
